polling + countdown timer
ripe-money/monitor pull request #10
Opened 2024-06-20 08:19 UTC by GiangNPham

close #8

2024-06-22 03:43 UTC, chucklam requested changes
Show time since last update, instead of time until next update.

2024-06-22 03:43 UTC, chucklam commented on app/page.tsx
> +  const pollTime: number = 15;
Make this a configurable parameter, in environment.

2024-06-22 04:17 UTC, chucklam requested changes

2024-06-22 04:17 UTC, chucklam commented on app/page.tsx
> +  }, 1000);
Instead of 1000, create a constant variable (ONE_SECOND??) and use that. This way it's easier to read.

2024-06-28 09:15 UTC, chucklam commented on app/page.tsx
> +  const pollTime: number = 15;
`pollTime` is unused and seems redundant with `pollTimeInSecond` below.

2024-06-28 09:20 UTC, chucklam commented on app/page.tsx
> +    process.env.NEXT_PUBLIC_POLL_TIME_IN_SECOND
When you add a configuration variable like this (`NEXT_PUBLIC_POLL_TIME_IN_SECOND`), document it in README. (In fact, document the whole process on what a developer needs to construct the `.env` file, without leaking any secret values.)

2024-06-28 09:28 UTC, chucklam commented on app/page.tsx
> +    process.env.NEXT_PUBLIC_POLL_TIME_IN_SECOND
Did your VSCode underline `process.env.NEXT_PUBLIC_POLL_TIME_IN_SECOND` in red? If not, you should check if eslint was installed properly. If it did, maybe you weren't sure what the error was about? Basically typescript was checking the possible types and realized that `process.env.NEXT_PUBLIC_POLL_TIME_IN_SECOND` could be undefined, which would cause a runtime error. The general solution is to check the variable is defined/valid at the top of the function. A possible alternative for this particular case is to default to some hardcoded value if the variable is not defined.

2024-06-30 01:22 UTC, GiangNPham commented on app/page.tsx
>    useEffect(() => {
i try to remove the useEffect but then the web will not fetch the status when it is first accessed (only after an amount of pollTimeInSecond)

2024-06-30 03:40 UTC, chucklam approved these changes
LGTM!

2024-06-30 04:33 UTC, merged