fetch status from Solana + Open Exchange and add icon to show status
ripe-money/monitor pull request #7
Opened 2024-06-13 03:58 UTC by GiangNPham

install axios to fetch API
add icon to the table to show dependency's status
close #6

2024-06-15 11:34 UTC, chucklam requested changes

2024-06-15 11:34 UTC, chucklam commented on app/page.tsx
> +        setDependencyList((preState) => [
Appending results to `dependencyList` will lead to issues when React mounts and unmounts components. (More below when talking about strict mode.) One way to get around it is to set all statuses together, like this:

```js
    const result = await Promise.all(
      dependencyURL.map(async (url) => {
        const { page, status } = await fetchStatus(url);
        const curStatus = status.indicator === "none" ? true : false;
        return { name: page.name, status: curStatus } as StatusModel;
      })
    );
    setStatuses(result);
```

2024-06-15 11:34 UTC, chucklam commented on next.config.mjs
> +  // config to disable reactStrictMode -> not render element twice
Think twice before changing defaults. They're there for a reason. Especially something like strict mode, which is there to improve security.

I assume you disabled strict mode because you read somewhere that React would call `useEffect` twice on each page in dev mode, and that's what was causing duplicates in the status page. Want to make sure you also read that [they have good reasons for calling `useEffect` twice](https://stackoverflow.com/a/72238236/6549597).

See my comment above about your appending to `dependencyList`, which was causing duplicates when `useEffect` is called twice. Fix that rather than turning off strict mode.

2024-06-16 00:53 UTC, GiangNPham commented on app/page.tsx
> +        setDependencyList((preState) => [
i have fixed my code locally and it worked without having to disabling reactStrictMode. However, I still did not understand how appending to the state will make the requests duplicated but not setting the state at once.

2024-06-18 10:04 UTC, chucklam requested changes
A couple really minor changes. I'll approve this after the changes.

2024-06-18 10:04 UTC, chucklam commented on app/utility/fetchStatus.ts
If the file is only exporting one thing, make sure the filename is the same as the exported function. Otherwise it's a bit confusing.

2024-06-18 10:32 UTC, chucklam commented on app/page.tsx
> +        setDependencyList((preState) => [
@GiangNPham Not sure if you've read the post about [React calling `useEffect` twice in dev mode](https://stackoverflow.com/questions/72238175/why-useeffect-running-twice-and-how-to-handle-it-well-in-react/72238236#72238236). Basically they do this in dev mode to remind developers that `useEffect` can be called multiple times under some user behavior, so training us to handle it.

If you got that point, then it may also help to add a `console.log(result)` right before this line:
```js
setStatuses(result);
```
You'll see that it's called twice when you're developing locally. Then note that this line that initializes `statuses` to an empty array is only called once:
```js
const [statuses, setStatuses] = useState<StatusModel[]>([]);
```

Thus if you update your statuses by appending to it (`setStatuses((preState) => ...`), it will expand by two rows each time `useEffect` is called. The new way using `setStatuses(result)` completely replaces the previous statuses with a new one, thus it will always be two rows.

One negative about this "solution" is that the UI (`statuses`) won't be updated until all the API calls are finished. And it's easy for the code to "hang" if one of the APIs timeout. To fully rewrite this, I would make `statuses` not an array of `StatusModel`, but a key/value pair where the key is the name of the dependency. The value would be a non-boolean status, including `up`, `down`, and `unknown`. With `unknown` meaning we haven't heard back from the status API. And you go back to updating one value at a time whenever an API result comes back.

That would be a lot of rewrite though, so let's punt that to the future. What we got is usable enough to go to production.

2024-06-20 04:10 UTC, chucklam approved these changes

2024-06-20 04:50 UTC, merged